[package]
name = "send-array-to-c"
version = "0.1.0"
authors = ["Markus Mayer <widemeadows@gmail.com>"]
edition = "2018"
build = "build.rs"
links = "array_utils"

[dependencies]

[build-dependencies]
cc = "1.0"
